### ISSUE TITLE
Allow disabling bubble animations

### ISSUE THREAD

**Issue by geoffrich** [Svelte-Sirens/svelte-sirens#13]
@ghostdevv brought this up in the Svelte Summit Discord chat after my talk so I thought I'd open an issue to capture my thoughts.

We should definitely be respecting prefers-reduced-motion for the bubbles. Since the animation is in pure CSS, we can turn it off in CSS using the media query (instead of relying on a Svelte store). Something like the following in `Bubble.svelte`...

```css
@media (prefers-reduced-motion: reduce) {
  .positioner  {
    animation: none;
  }
}
```

However, this would only turn off the bubbles if the user enabled reduced motion in their OS settings. Not everyone knows about that setting, and this is a large enough animation that it would be good to implement a [dedicated toggle](https://www.smashingmagazine.com/2021/10/respecting-users-motion-preferences/#explicit-motion-toggle). This would make it easy for users to disable animations for just this site. 

Not sure how this would look design-wise, but we could probably implement with a custom Svelte store.

**Comment by brittneypostma** [comment]
Thank you for bringing it to our attention. We definitely want to respect users and make the site more accessible. I will come up with a way to add in a toggle.

**Comment by ghostdevv** [comment]
It looks like we already had a prefers-reduced-motion system built into brittneys css reset! I am going to add this directly incase anything gets changed though

**Comment by geoffrich** [comment]
Ah, can't believe I missed that it was already there! Thanks for looking into it.

Re: dedicated motion toggle - one of my favorite examples is the [Animal Crossing site](https://animal-crossing.com/).

**Comment by brittneypostma** [comment]
Thanks for the example, that's great.

**Comment by ghostdevv** [comment]
Thanks @geoffrich !
