### ISSUE TITLE
Switch to PNPM

### ISSUE THREAD

**Issue by brittneypostma** [Svelte-Sirens/svelte-sirens#19]
Going to make the switch over to pnpm I think.

**Comment by spences10** [comment]
![do it](https://c.tenor.com/cJ9V22mZIG0AAAAC/do-it-just-do-it.gif)

**Comment by brittneypostma** [comment]
Reopening to explore in response to this post. https://twitter.com/BrittneyPostma/status/1486479922801659905?s=20

**Comment by ghostdevv** [comment]
I really want pnpm but I still with the opinion that it's easier to wait for native support. However not opposed to it so if it's wanted then go for it

**Comment by brittneypostma** [comment]
Completed in #80 now that Netlify has full pnpm support 🥳
