### ISSUE TITLE
Better organize style files into a design system

### ISSUE THREAD

**Issue by brittneypostma** [Svelte-Sirens/svelte-sirens#20]
Break out styles relevant into a design system for organization.

**Comment by brittneypostma** [comment]
I'm going to try adding Open Props and check it out in a branch.

**Comment by brittneypostma** [comment]
Here are the relevant files if you want to take a look @ghostdevv 
[https://github.com/brittneypostma/sveltekit-open-jit-props-starter](https://github.com/brittneypostma/sveltekit-open-jit-props-starter)

**Comment by ghostdevv** [comment]
I only just saw this @brittneypostma - buried in dependabot notifications xD Did you end up adding open props?

**Comment by brittneypostma** [comment]
Yeah, I merged it in
