### ISSUE TITLE
Add fallback page for building with adapter static

### ISSUE THREAD

**Issue by spences10** [Svelte-Sirens/svelte-sirens#24]
@ghostdevv told me about this today, I thought that the `__error.svelte` would cover not found errors but looks like this works on a server environment (like with Vercel)

Using adapter static you can define a fallback page here's the docs: https://kit.svelte.dev/docs#adapters-creating-a-static-site

And the relevant detail on the adapter static readme: https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode

**Comment by spences10** [comment]
Looks like this might be a none starter here, from the `adapter-static` docs:

> In most situations this is not recommended: it harms SEO, tends to slow down perceived performance, and makes your app inaccessible to users if JavaScript fails or is disabled (which happens [more often than you probably think](https://kryogenix.org/code/browser/everyonehasjs.html)).

So, I'll leave this open for discussion. 

If everyone is happy to close it then let me know.

**Comment by brittneypostma** [comment]
https://github.com/Svelte-Sirens/svelte-sirens/commit/4d3fdfdf67266a2691ad296c0160a69dd49316d9

This change I made broke the site so I'm not sure how to get it working.

**Comment by ghostdevv** [comment]
I feel like we should just leave the fallback for now @brittneypostma

**Comment by brittneypostma** [comment]
> I feel like we should just leave the fallback for now @brittneypostma 

It broke the site completely.

**Comment by ghostdevv** [comment]
Can this be closed?

**Comment by brittneypostma** [comment]
Still think we may need something there. Here is a Reddit thread about it https://www.reddit.com/r/sveltejs/comments/o1tr4w/sveltekit_adapterstatic_nonspa_error_pages/

404s still don't pull the correct error page

https://sveltesirens.dev/speakers/brittney-postma2
