### ISSUE TITLE
Form for Speaker Submissions

### ISSUE THREAD

**Issue by brittneypostma** [Svelte-Sirens/svelte-sirens#26]
Add google form to site for speaker submissions.

**Comment by spences10** [comment]
There could be a GraphCMS mutation to add that straight to a draft for approval by a content editor

**Comment by spences10** [comment]
@brittneypostma could you be a bit more specific on what's needed for this and I'll implement something so that speakers can submit a talk.

Here's my guess at what's needed:

- Submission model
	- Speaker name
	- Handle
	- Multi line text or markdown input for submission outline

We can create a `submission.json.js` endpoint to a `post` to the GraphCMS API from a form input on a page

**Comment by brittneypostma** [comment]
We need a form for this from Google. I think Gen is going to work on doing that and not sure everything we need yet. Probably everything in the speaker and event models in graphCMS

**Comment by coderinheels** [comment]
A Svelte Sirens **Call for Speakers Page** has been created on the **Sessionize** Platform.  The link is https://sessionize.com/sveltesirens.  I believe aside from adding a link, the form itself can also be embedded to websites

**Comment by coderinheels** [comment]
Sessionize is good to go - website-wise https://github.com/Svelte-Sirens/svelte-sirens/issues/42#issuecomment-1003034113

**Comment by brittneypostma** [comment]
> @brittneypostma could you be a bit more specific on what's needed for this and I'll implement something so that speakers can submit a talk.
> 
> Here's my guess at what's needed:
> 
> * Submission model
>   
>   * Speaker name
>   * Handle
>   * Multi line text or markdown input for submission outline
> 
> We can create a `submission.json.js` endpoint to a `post` to the GraphCMS API from a form input on a page

I actually really like this idea Scott. Maybe we could do this on stream? I'm working on those latest and upcoming queries right now I spoke about yesterday, but should finish that up today.

**Comment by brittneypostma** [comment]
This could actually resolve the issue of sending people to outside services to book. And provide an easier way to manage them. I would like to scrape their image from twitter and generate the thumbnail image too. We do this on coding cat with cloudinary.

**Comment by ghostdevv** [comment]
Don't forget that talks should go into a "review stage" before being accepted

**Comment by brittneypostma** [comment]
> Don't forget that talks should go into a "review stage" before being accepted

I think this is more for speaker submissions, they wouldn't be submitting their talk here. People are booking with the intention of recording a talk later. I think that part is going to have to stay manual.

**Comment by ghostdevv** [comment]
What do you mean by speaker submissions? @brittneypostma

**Comment by brittneypostma** [comment]
People who want to give talks.

**Comment by ghostdevv** [comment]
If we plan to have an internal discord server then a form can be easily implimented where they submit their name, idea date range, preffered contact method, etc and it just sends a message in the discord

**Comment by spences10** [comment]
> This could actually resolve the issue of sending people to outside services to book. And provide an easier way to manage them. I would like to scrape their image from twitter and generate the thumbnail image too. We do this on coding cat with cloudinary.

So, if using the CMS for this step, which from looking at the issue here it looks like Sessionize was decided on??

Aside from that, there could be a form to submit to GraphCMS, the default stage for the submission can be set to draft then reviewed and have the stage (draft/published) set.

**Comment by brittneypostma** [comment]
That sounds like a decent workflow. We are revisiting this issue in our March catch up call. If sessionize isn't working out, we may try this option. Thanks @spences10

**Comment by brittneypostma** [comment]
Revisiting this issue. We've still been using sessionize and have only gotten a couple of responses. I'm in favor of moving to a form on the site. I would like to discuss options for handling responses. We can possibly add in the discord functionally @ghostdevv was mentioning at a later time.

**Comment by ghostdevv** [comment]
the discord thing would be super easy to do

**Comment by brittneypostma** [comment]
@ghostdevv I think having a discord thing would be great, I just wonder if people will know to use it. We can always test it out and see. Would it be a command like `/sirens-speaker` or something along those lines and work in any chat channel? Would it also need a backend to handle form responses or could it be sent to the gmail account directly?

I was going to tag Kev here, but realized he's not in the org. I think for the stream in a couple weeks that we can show off forms and form actions, but I would really prefer to then just use [Netlify forms](https://docs.netlify.com/forms/setup/). This will prevent us from having to have a form management system. The responses will go directly through the Netlify dashboard and I can setup the email notification for it to our gmail.

**Comment by brittneypostma** [comment]
yeah, i guess discord could work for this as long as it pings us which i assume it will

**Comment by brittneypostma** [comment]
we will try and set this up on the stream and see how it goes

**Comment by ghostdevv** [comment]
I can do the discord integration, if you wanna handle the UI part?

**Comment by ghostdevv** [comment]
oh unless you wanna do the entire thing on that form actions stream?

**Comment by brittneypostma** [comment]
Yeah, I want to do it on the stream this week. I just wanted to have a plan going in.
