### ISSUE TITLE
Update Language to 'Non-binary people'

### ISSUE THREAD

**Issue by stordahl** [Svelte-Sirens/svelte-sirens#29]
Hey y'all! I wanted to start-up a conversation about the use of 'non-binary' in Svelte Sirens materials, as the term is not analogous to 'men' or 'women' (at least not grammatically). Updating the language to 'non-binary people' may eliminate confusion for non-binary people. I really appreciate that y'all are being inclusive of people like me, and just want to make sure no one feels misrepresented or gets confused by this language.

**Comment by ghostdevv** [comment]
Thank you for letting us know! Would you be interested in doing a pr for this? @stordahl

**Comment by stordahl** [comment]
@ghostdevv Absolutely!

**Comment by ghostdevv** [comment]
Amazing!

**Comment by brittneypostma** [comment]
> Hey y'all! I wanted to start-up a conversation about the use of 'non-binary' in Svelte Sirens materials, as the term is not analogous to 'men' or 'women' (at least not grammatically). Updating the language to 'non-binary people' may eliminate confusion for non-binary people. I really appreciate that y'all are being inclusive of people like me, and just want to make sure no one feels misrepresented or gets confused by this language. 

Thank you so much for pointing this out and definitely don't want confusion. If you don't get to it, I will be working on all issues tomorrow and will take care of this immediately!

**Comment by stordahl** [comment]
Thanks Brittany! Appreciate your work 🤗

**Comment by ghostdevv** [comment]
Thanks @brittneypostma and @stordahl !
