### ISSUE TITLE
Hide past events

### ISSUE THREAD

**Issue by ghostdevv** [Svelte-Sirens/svelte-sirens#40]
Instead of removing past events from graphcms add some sort of query to check timestamps in the GQL request?

@spences10 if you have time do you know how to do this in the query? :sweat_smile:

**Comment by spences10** [comment]
Yep, you can manage this with a where clause:

Here's an example I put together on a blog project, should be the same for the Sirens GraphCMS project.

```graphql
query Filter {
  posts(where: {date_gt: "2020-05-05"}) {
    title
  }
}

query NoFilter {
  posts {
    title
  }
}
```

**Comment by ghostdevv** [comment]
Thank you! @spences10
