### ISSUE TITLE
Event management

### ISSUE THREAD

**Issue by brittneypostma** [Svelte-Sirens/svelte-sirens#42]
We have been using luma so far and it works, but I would like a way to add an add to calendar button on each event. The YT video also has a reminder after it is created in streamyard. I’m looking for ideas and the best way to implement this to retain people and help remind them of events. In this same regard, I’m thinking about the registration piece and getting emails out for events also. I wonder if this could be done from Svelte Society mailing list as well?

**Comment by brittneypostma** [comment]
Sessionize has also been added to be explored

**Comment by spences10** [comment]
I think Sessionize is a pretty neat tool with email prompts, I've not heard of Luma

Sessionize will be for speakers and I'm presuming for attendees then there will need to be a collection of email addresses to send a notification before it starts, right?

So, there's Twilio's SendGrid you could use for email lists, I'm familiar with that, and also Revue whic could be integrated into the Twitter account.

**Comment by coderinheels** [comment]
Sessionize is a very good platform for managing speakers and their talk proposals, but not for managing event attendees (it's not meant for that).

Svelte Sirens will do some roadmap planning to see which tools will be best to handle certain things.

**Comment by brittneypostma** [comment]
I despise having 50 platforms that all handle different things. It is literally one of the best and worst parts of the jamstack. This is why I think having a database with Fauna is a good idea, just to keep all our stuff located in one place. I don't think we need something like Builder.io or Uniform.dev, but dangit, it would make it easier.

**Comment by brittneypostma** [comment]
Just checked out learnwithjason.dev and he has a google calendar for his shows and shares that on his site. That would be an option for us as well, since we have the gmail we could create the events on.

**Comment by brittneypostma** [comment]
I would like to use something like this share button too, where a specific event could be shared in multiple ways.
![image](https://user-images.githubusercontent.com/45889730/147717862-b33cdc45-2d4b-40ff-8b1a-8141660dc2bd.png)

**Comment by coderinheels** [comment]
Svelte Sirens' Sessionize Page has been live for a few days and can now be added / embedded to the website

**Comment by brittneypostma** [comment]
> Svelte Sirens' Sessionize Page has been live for a few days and can now be added / embedded to the website

That is issue #26, this is for sharing events and adding a calendar reminder to the site for the events.

**Comment by coderinheels** [comment]
Ok, since this thread has several references to Sessionize, too, my comment still stands.  Thanks for mentioning #26 here

**Comment by brittneypostma** [comment]
Add live streams to events and any past talks on talks route. Filter how ghostdev.xyz/posts is.

**Comment by brittneypostma** [comment]
@ghostdevv would you be willing to work on this one? I think I just went the route of separating the talks and streams for now, but we could combine them to add this filtering technique in.

**Comment by ghostdevv** [comment]
I can @brittneypostma
