### ISSUE TITLE
Some +page.js should be +page.server.js

### ISSUE THREAD

**Issue by ghostdevv** [Svelte-Sirens/svelte-sirens#70]
Data should only be loaded on the server

**Comment by lukeshafer** [comment]
Hi @ghostdevv! I'd be happy to tackle this one!

**Comment by ghostdevv** [comment]
@lukeshafer Go for it!

**Comment by lukeshafer** [comment]
Huh it may have been taken care of already? I just see one +page.js in the calendar route, which is just doing a redirect! So we may be good here, unless I'm misreading/misunderstanding! 

I'd love to help where needed though! I'll glance through the other issues to see

**Comment by ghostdevv** [comment]
Oh weird :/ Sorry about that! We could probably do with that `+page.js` being made a `+page.server.ts` though if you want to do that, I also marked #67 as a good first issue

If you have already done a fork make sure to update it, I pushed a couple changes that fix a couple errors we had that are important you get ;)

**Comment by lukeshafer** [comment]
Sounds good 😁 I'll update my fork and take a look at that one and I'll update that endpoint!

**Comment by ghostdevv** [comment]
thanks for all your help @lukeshafer
