### ISSUE TITLE
Replace @ aliases with $

### ISSUE THREAD

**Issue by ghostdevv** [Svelte-Sirens/svelte-sirens#78]
Make it align with SvelteKit's aliases - I also used to prefer the `@` but now I much prefer the `$` as it's what I am used to :rofl: 

Thoughts? @brittneypostma

**Comment by brittneypostma** [comment]
That's fine with me. $everywhere 😅

**Comment by brittneypostma** [comment]
single use components can be moved into the routes directory with this move

**Comment by vaishnav-mk** [comment]
Hey, could this be assigned to me? I'd love to work on this!
